### ISSUE TITLE
UIButton don't work

### ISSUE THREAD

**Issue by paulfavier** [nicklockwood/CubeController#2]
Hi :) First thing, thx for this work it's so cool !!

When i add a button on the latest uiViewcontroller, i can't click on it ...

Do you have an idea ? 

Thx a lot !

**Comment by nicklockwood** [comment]
Can you explain what you mean by "latest"?

**Comment by paulfavier** [comment]
Oh sorry for my english ^^ i have 3 viewController, for me the latest is the third on the right :)

**Comment by nicklockwood** [comment]
Do you have buttons that work correctly on the other controllers?

**Comment by nicklockwood** [comment]
Yes, I think I see the problem. I'll fix it.

**Comment by paulfavier** [comment]
Can you tell me more ? i like to understand the problem :)

**Comment by nicklockwood** [comment]
When you rotate the views, although the 3rd view appears to be in front in 3D dimensions, UIKit events are propagated according to the order of views in their superview.

So one of the views on your first view controller is most likely intercepting the taps, preventing them from reaching the button on your third view controller (the one that appears to be in front).

**Comment by paulfavier** [comment]
ok i understand thx ! I would like to use this for my school project, do you think it's hard to fix ?

**Comment by nicklockwood** [comment]
I've fixed it.

**Comment by paulfavier** [comment]
Ahahah seriously ? You are awesome !

**Comment by nicklockwood** [comment]
Yep :-) Fixed in 1.0.1.

**Comment by paulfavier** [comment]
Thx a lot !!
