### ISSUE TITLE
not working with tableview

### ISSUE THREAD

**Issue by xinwo** [nicklockwood/CubeController#6]
as title.
I think it is a bug.
No offence, just want to know if you are still maintaining this project.

**Comment by nicklockwood** [comment]
That's not really a very helpful bug report :-)

Here's an app that uses CubeController with tableview and seems to work OK.

https://github.com/nicklockwood/Concurrency

**Comment by xinwo** [comment]
Sorry to bother you.
Thank you for the app. I'll check it.

**Comment by nicklockwood** [comment]
No problem.
